"""Seed definitions for the global template catalog (Task 11.1, Req 11).

Provides the ready-made project templates the platform ships with:

- **Student** (Req 11.1): Temperature Monitor, Water Level, Soil Moisture,
  Energy Meter.
- **Company** (Req 11.3): Water Tank, Pump Control, Cold Storage,
  Smart Agriculture, Industrial Motor.

Each template carries Arduino source code and a wiring diagram (Req 11.2) plus a
``dashboard_def`` and ``rules_def`` used when the template is applied to a device
(Req 11.4). The definitions are pure data so they can be seeded into any
database (Alembic data migration, a management command, or a test fixture) via
:func:`seed_templates`.
"""

from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.infra import Template

# ---------------------------------------------------------------------------
# Reusable Arduino sketch skeletons (kept short; real firmware is generated by
# the Web Flasher pipeline). Each ends with a publish to the device's telemetry
# topic, matching the MQTT contract iotaps/{org_id}/{device_id}/telemetry.
# ---------------------------------------------------------------------------
def _arduino_sketch(sensor_comment: str, read_body: str) -> str:
    """Build a minimal ESP32 sketch publishing a JSON telemetry payload."""
    return (
        "#include <WiFi.h>\n"
        "#include <PubSubClient.h>\n"
        "\n"
        "// " + sensor_comment + "\n"
        "WiFiClient espClient;\n"
        "PubSubClient mqtt(espClient);\n"
        "\n"
        "void setup() {\n"
        "  Serial.begin(115200);\n"
        "  WiFi.begin(\"SSID\", \"PASSWORD\");\n"
        "  mqtt.setServer(\"BROKER_HOST\", 1883);\n"
        "}\n"
        "\n"
        "void loop() {\n"
        "  if (!mqtt.connected()) mqtt.connect(\"DEVICE_ID\", \"MQTT_USER\", \"MQTT_PASS\");\n"
        + read_body
        + "  delay(60000); // default 60s interval\n"
        "}\n"
    )


# ---------------------------------------------------------------------------
# Student templates (Req 11.1, 11.2)
# ---------------------------------------------------------------------------
_STUDENT_TEMPLATES: list[dict] = [
    {
        "category": "student",
        "name": "Temperature Monitor",
        "arduino_code": _arduino_sketch(
            "DS18B20 / DHT22 temperature sensor on GPIO4",
            "  float temp = readTemperature();\n"
            "  char payload[64];\n"
            "  snprintf(payload, sizeof(payload), \"{\\\"temp\\\": %.1f}\", temp);\n"
            "  mqtt.publish(\"iotaps/ORG/DEVICE/telemetry\", payload);\n",
        ),
        "wiring_diagram_url": "/static/templates/student/temperature-monitor.svg",
        "dashboard_def": {
            "name": "Temperature Monitor",
            "widgets": [
                {"type": "gauge", "config": {"metric": "temp", "unit": "C", "min": -10, "max": 60}},
                {"type": "line", "config": {"metric": "temp", "unit": "C"}},
                {"type": "value", "config": {"metric": "temp", "unit": "C"}},
            ],
        },
        "rules_def": {
            "rules": [
                {
                    "name": "High temperature alert",
                    "enabled": True,
                    "nodes": [
                        {"id": "t", "node_type": "trigger", "config": {"metric": "temp"}},
                        {"id": "c", "node_type": "condition", "config": {"op": ">", "value": 40}},
                        {"id": "a", "node_type": "action", "config": {"type": "notify", "message": "Temperature high"}},
                    ],
                    "edges": [{"from": "t", "to": "c"}, {"from": "c", "to": "a"}],
                }
            ]
        },
    },
    {
        "category": "student",
        "name": "Water Level",
        "arduino_code": _arduino_sketch(
            "Ultrasonic HC-SR04 water level sensor (trig GPIO5, echo GPIO18)",
            "  float level = readWaterLevelPercent();\n"
            "  char payload[64];\n"
            "  snprintf(payload, sizeof(payload), \"{\\\"level\\\": %.1f}\", level);\n"
            "  mqtt.publish(\"iotaps/ORG/DEVICE/telemetry\", payload);\n",
        ),
        "wiring_diagram_url": "/static/templates/student/water-level.svg",
        "dashboard_def": {
            "name": "Water Level",
            "widgets": [
                {"type": "gauge", "config": {"metric": "level", "unit": "%", "min": 0, "max": 100}},
                {"type": "line", "config": {"metric": "level", "unit": "%"}},
            ],
        },
        "rules_def": {
            "rules": [
                {
                    "name": "Low water level alert",
                    "enabled": True,
                    "nodes": [
                        {"id": "t", "node_type": "trigger", "config": {"metric": "level"}},
                        {"id": "c", "node_type": "condition", "config": {"op": "<", "value": 20}},
                        {"id": "a", "node_type": "action", "config": {"type": "notify", "message": "Water level low"}},
                    ],
                    "edges": [{"from": "t", "to": "c"}, {"from": "c", "to": "a"}],
                }
            ]
        },
    },
    {
        "category": "student",
        "name": "Soil Moisture",
        "arduino_code": _arduino_sketch(
            "Capacitive soil moisture sensor on ADC GPIO34",
            "  int moisture = readSoilMoisturePercent();\n"
            "  char payload[64];\n"
            "  snprintf(payload, sizeof(payload), \"{\\\"moisture\\\": %d}\", moisture);\n"
            "  mqtt.publish(\"iotaps/ORG/DEVICE/telemetry\", payload);\n",
        ),
        "wiring_diagram_url": "/static/templates/student/soil-moisture.svg",
        "dashboard_def": {
            "name": "Soil Moisture",
            "widgets": [
                {"type": "gauge", "config": {"metric": "moisture", "unit": "%", "min": 0, "max": 100}},
                {"type": "line", "config": {"metric": "moisture", "unit": "%"}},
            ],
        },
        "rules_def": {
            "rules": [
                {
                    "name": "Dry soil alert",
                    "enabled": True,
                    "nodes": [
                        {"id": "t", "node_type": "trigger", "config": {"metric": "moisture"}},
                        {"id": "c", "node_type": "condition", "config": {"op": "<", "value": 30}},
                        {"id": "a", "node_type": "action", "config": {"type": "notify", "message": "Soil is dry"}},
                    ],
                    "edges": [{"from": "t", "to": "c"}, {"from": "c", "to": "a"}],
                }
            ]
        },
    },
    {
        "category": "student",
        "name": "Energy Meter",
        "arduino_code": _arduino_sketch(
            "PZEM-004T / ACS712 current sensor for energy metering",
            "  float power = readActivePowerW();\n"
            "  char payload[64];\n"
            "  snprintf(payload, sizeof(payload), \"{\\\"power\\\": %.1f}\", power);\n"
            "  mqtt.publish(\"iotaps/ORG/DEVICE/telemetry\", payload);\n",
        ),
        "wiring_diagram_url": "/static/templates/student/energy-meter.svg",
        "dashboard_def": {
            "name": "Energy Meter",
            "widgets": [
                {"type": "value", "config": {"metric": "power", "unit": "W"}},
                {"type": "line", "config": {"metric": "power", "unit": "W"}},
                {"type": "bar", "config": {"metric": "power", "unit": "W"}},
            ],
        },
        "rules_def": {
            "rules": [
                {
                    "name": "Power overload alert",
                    "enabled": True,
                    "nodes": [
                        {"id": "t", "node_type": "trigger", "config": {"metric": "power"}},
                        {"id": "c", "node_type": "condition", "config": {"op": ">", "value": 2000}},
                        {"id": "a", "node_type": "action", "config": {"type": "notify", "message": "Power overload"}},
                    ],
                    "edges": [{"from": "t", "to": "c"}, {"from": "c", "to": "a"}],
                }
            ]
        },
    },
]


# ---------------------------------------------------------------------------
# Company templates (Req 11.3, 11.2)
# ---------------------------------------------------------------------------
_COMPANY_TEMPLATES: list[dict] = [
    {
        "category": "company",
        "name": "Water Tank",
        "arduino_code": _arduino_sketch(
            "Submersible pressure level sensor + relay pump control",
            "  float level = readTankLevelPercent();\n"
            "  char payload[64];\n"
            "  snprintf(payload, sizeof(payload), \"{\\\"level\\\": %.1f}\", level);\n"
            "  mqtt.publish(\"iotaps/ORG/DEVICE/telemetry\", payload);\n",
        ),
        "wiring_diagram_url": "/static/templates/company/water-tank.svg",
        "dashboard_def": {
            "name": "Water Tank",
            "widgets": [
                {"type": "gauge", "config": {"metric": "level", "unit": "%", "min": 0, "max": 100}},
                {"type": "line", "config": {"metric": "level", "unit": "%"}},
                {"type": "toggle", "config": {"command": "pump"}},
            ],
        },
        "rules_def": {
            "rules": [
                {
                    "name": "Auto-fill on low level",
                    "enabled": True,
                    "nodes": [
                        {"id": "t", "node_type": "trigger", "config": {"metric": "level"}},
                        {"id": "c", "node_type": "condition", "config": {"op": "<", "value": 25}},
                        {"id": "a", "node_type": "action", "config": {"type": "command", "command": "pump", "value": "on"}},
                    ],
                    "edges": [{"from": "t", "to": "c"}, {"from": "c", "to": "a"}],
                }
            ]
        },
    },
    {
        "category": "company",
        "name": "Pump Control",
        "arduino_code": _arduino_sketch(
            "Relay-driven pump with current sensing for dry-run protection",
            "  float current = readPumpCurrentA();\n"
            "  char payload[64];\n"
            "  snprintf(payload, sizeof(payload), \"{\\\"current\\\": %.2f}\", current);\n"
            "  mqtt.publish(\"iotaps/ORG/DEVICE/telemetry\", payload);\n",
        ),
        "wiring_diagram_url": "/static/templates/company/pump-control.svg",
        "dashboard_def": {
            "name": "Pump Control",
            "widgets": [
                {"type": "value", "config": {"metric": "current", "unit": "A"}},
                {"type": "toggle", "config": {"command": "pump"}},
                {"type": "line", "config": {"metric": "current", "unit": "A"}},
            ],
        },
        "rules_def": {
            "rules": [
                {
                    "name": "Dry-run protection",
                    "enabled": True,
                    "nodes": [
                        {"id": "t", "node_type": "trigger", "config": {"metric": "current"}},
                        {"id": "c", "node_type": "condition", "config": {"op": "<", "value": 0.5}},
                        {"id": "a", "node_type": "action", "config": {"type": "command", "command": "pump", "value": "off"}},
                    ],
                    "edges": [{"from": "t", "to": "c"}, {"from": "c", "to": "a"}],
                }
            ]
        },
    },
    {
        "category": "company",
        "name": "Cold Storage",
        "arduino_code": _arduino_sketch(
            "Temperature + humidity probe for refrigerated storage",
            "  float temp = readTemperature();\n"
            "  float hum = readHumidity();\n"
            "  char payload[96];\n"
            "  snprintf(payload, sizeof(payload), \"{\\\"temp\\\": %.1f, \\\"hum\\\": %.1f}\", temp, hum);\n"
            "  mqtt.publish(\"iotaps/ORG/DEVICE/telemetry\", payload);\n",
        ),
        "wiring_diagram_url": "/static/templates/company/cold-storage.svg",
        "dashboard_def": {
            "name": "Cold Storage",
            "widgets": [
                {"type": "gauge", "config": {"metric": "temp", "unit": "C", "min": -30, "max": 20}},
                {"type": "gauge", "config": {"metric": "hum", "unit": "%", "min": 0, "max": 100}},
                {"type": "alert_badge", "config": {"metric": "temp"}},
            ],
        },
        "rules_def": {
            "rules": [
                {
                    "name": "Temperature excursion alert",
                    "enabled": True,
                    "nodes": [
                        {"id": "t", "node_type": "trigger", "config": {"metric": "temp"}},
                        {"id": "c", "node_type": "condition", "config": {"op": ">", "value": 8}},
                        {"id": "d", "node_type": "delay", "config": {"seconds": 300}},
                        {"id": "a", "node_type": "action", "config": {"type": "notify", "message": "Cold storage too warm"}},
                    ],
                    "edges": [
                        {"from": "t", "to": "c"},
                        {"from": "c", "to": "d"},
                        {"from": "d", "to": "a"},
                    ],
                }
            ]
        },
    },
    {
        "category": "company",
        "name": "Smart Agriculture",
        "arduino_code": _arduino_sketch(
            "Soil moisture + temperature + irrigation valve relay",
            "  int moisture = readSoilMoisturePercent();\n"
            "  float temp = readTemperature();\n"
            "  char payload[96];\n"
            "  snprintf(payload, sizeof(payload), \"{\\\"moisture\\\": %d, \\\"temp\\\": %.1f}\", moisture, temp);\n"
            "  mqtt.publish(\"iotaps/ORG/DEVICE/telemetry\", payload);\n",
        ),
        "wiring_diagram_url": "/static/templates/company/smart-agriculture.svg",
        "dashboard_def": {
            "name": "Smart Agriculture",
            "widgets": [
                {"type": "gauge", "config": {"metric": "moisture", "unit": "%", "min": 0, "max": 100}},
                {"type": "gauge", "config": {"metric": "temp", "unit": "C", "min": -10, "max": 60}},
                {"type": "toggle", "config": {"command": "irrigation"}},
                {"type": "line", "config": {"metric": "moisture", "unit": "%"}},
            ],
        },
        "rules_def": {
            "rules": [
                {
                    "name": "Auto-irrigation on dry soil",
                    "enabled": True,
                    "nodes": [
                        {"id": "t", "node_type": "trigger", "config": {"metric": "moisture"}},
                        {"id": "c", "node_type": "condition", "config": {"op": "<", "value": 35}},
                        {"id": "a", "node_type": "action", "config": {"type": "command", "command": "irrigation", "value": "on"}},
                    ],
                    "edges": [{"from": "t", "to": "c"}, {"from": "c", "to": "a"}],
                }
            ]
        },
    },
    {
        "category": "company",
        "name": "Industrial Motor",
        "arduino_code": _arduino_sketch(
            "Vibration + temperature monitoring for motor predictive maintenance",
            "  float vibration = readVibrationMmS();\n"
            "  float temp = readBearingTempC();\n"
            "  char payload[96];\n"
            "  snprintf(payload, sizeof(payload), \"{\\\"vibration\\\": %.2f, \\\"temp\\\": %.1f}\", vibration, temp);\n"
            "  mqtt.publish(\"iotaps/ORG/DEVICE/telemetry\", payload);\n",
        ),
        "wiring_diagram_url": "/static/templates/company/industrial-motor.svg",
        "dashboard_def": {
            "name": "Industrial Motor",
            "widgets": [
                {"type": "line", "config": {"metric": "vibration", "unit": "mm/s"}},
                {"type": "gauge", "config": {"metric": "temp", "unit": "C", "min": 0, "max": 150}},
                {"type": "alert_badge", "config": {"metric": "vibration"}},
            ],
        },
        "rules_def": {
            "rules": [
                {
                    "name": "Excess vibration alert",
                    "enabled": True,
                    "nodes": [
                        {"id": "t", "node_type": "trigger", "config": {"metric": "vibration"}},
                        {"id": "c", "node_type": "condition", "config": {"op": ">", "value": 7.1}},
                        {"id": "a", "node_type": "action", "config": {"type": "notify", "message": "Motor vibration high"}},
                    ],
                    "edges": [{"from": "t", "to": "c"}, {"from": "c", "to": "a"}],
                }
            ]
        },
    },
]


# All seed templates (4 student + 5 company = 9).
TEMPLATE_SEEDS: list[dict] = _STUDENT_TEMPLATES + _COMPANY_TEMPLATES


async def seed_templates(session: AsyncSession) -> int:
    """Insert any missing catalog templates, idempotently by (category, name).

    Returns the number of templates inserted. Existing templates (matched on
    ``category`` + ``name``) are left untouched so reseeding is safe.
    """
    inserted = 0
    for spec in TEMPLATE_SEEDS:
        existing = await session.execute(
            select(Template.id).where(
                Template.category == spec["category"],
                Template.name == spec["name"],
            )
        )
        if existing.first() is not None:
            continue
        session.add(Template(**spec))
        inserted += 1
    if inserted:
        await session.commit()
    return inserted
