// Generates a ready-to-compile Arduino "Blink LED" sketch for a specific
// IoTAPS device, with the device's generated token (device id) baked in.
//
// The sketch mirrors the platform's MQTT contract (topics + on/off/value
// command shape + ACK, design.md "MQTT topics & payloads"): it connects to
// Wi-Fi and the IoTAPS broker, toggles the built-in LED in response to dashboard
// commands, and publishes telemetry every 5 seconds.
//
// Implementation note: the embedded C++ deliberately uses NO backslash escapes
// (raw-string literals `R"(...)"` for JSON, and Serial.print/println instead of
// `\n`) so this JS template literal emits the source verbatim — only the
// `${...}` placeholders below are substituted.

/** Default broker host; overridable via VITE_MQTT_HOST or the UI. */
export const DEFAULT_MQTT_HOST =
  (typeof import.meta !== "undefined" && import.meta.env?.VITE_MQTT_HOST) ||
  "mqtt.iotaps.com";

export const DEFAULT_MQTT_PORT = 1883;

/**
 * Build the Blink-LED demo sketch.
 * @param {object} opts
 * @param {string} opts.token   Device token (generated id) — required.
 * @param {string} [opts.label] Friendly device label for the header comment.
 * @param {string} [opts.host]  MQTT broker host.
 * @param {number} [opts.port]  MQTT broker port.
 * @param {string} [opts.ssid]  Wi-Fi SSID placeholder.
 * @param {string} [opts.password] Wi-Fi password placeholder.
 * @returns {string} the .ino source.
 */
export function buildBlinkSketch({
  token,
  label,
  host = DEFAULT_MQTT_HOST,
  port = DEFAULT_MQTT_PORT,
  ssid = "YOUR_WIFI_SSID",
  password = "YOUR_WIFI_PASSWORD",
} = {}) {
  const tk = token || "PASTE_YOUR_DEVICE_TOKEN";
  const deviceName = label ? `${label} ` : "";
  return `/*
 * IoTAPS - Blink LED Demo (ESP32)
 * Auto-generated for device ${deviceName}by IoTAPS.
 *
 * Device token (generated id): ${tk}
 *
 * What it does:
 *   - Connects to Wi-Fi and the IoTAPS MQTT broker.
 *   - Toggles the built-in LED when you press a Toggle/Slider widget
 *     on your dashboard (on / off / value commands).
 *   - Publishes telemetry { led, uptime, wifi_rssi } every 5 seconds.
 *
 * Libraries (install from Arduino Library Manager):
 *   - PubSubClient (by Nick O'Leary)
 *   - ArduinoJson  (by Benoit Blanchon)
 */
#include <WiFi.h>
#include <PubSubClient.h>
#include <ArduinoJson.h>

// ---- Wi-Fi ----
const char* WIFI_SSID     = "${ssid}";
const char* WIFI_PASSWORD = "${password}";

// ---- IoTAPS connection ----
const char* IOTAPS_SERVER = "${host}";
const int   IOTAPS_PORT   = ${port};
const char* DEVICE_TOKEN  = "${tk}";   // generated by IoTAPS - used as id + login

#define LED_PIN 2               // built-in LED on most ESP32 dev boards
#define TELEMETRY_INTERVAL 5000 // ms

WiFiClient espClient;
PubSubClient mqtt(espClient);

String topicTelemetry;
String topicCommand;
String topicStatus;
String topicAck;

bool ledState = false;
unsigned long lastTelemetry = 0;

void connectWiFi() {
  Serial.print("[WiFi] Connecting to ");
  Serial.println(WIFI_SSID);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println();
  Serial.print("[WiFi] Connected. IP: ");
  Serial.println(WiFi.localIP());
}

void publishTelemetry() {
  StaticJsonDocument<128> doc;
  doc["led"] = ledState ? 1 : 0;
  doc["uptime"] = millis() / 1000;
  doc["wifi_rssi"] = WiFi.RSSI();

  char buffer[128];
  serializeJson(doc, buffer);
  mqtt.publish(topicTelemetry.c_str(), buffer);
  Serial.print("[TX] ");
  Serial.println(buffer);
}

void onCommand(char* topic, byte* payload, unsigned int length) {
  StaticJsonDocument<192> doc;
  if (deserializeJson(doc, payload, length)) return;

  const char* type  = doc["type"] | "";
  const char* cmdId = doc["command_id"] | "";

  if (strcmp(type, "on") == 0) {
    ledState = true;
    digitalWrite(LED_PIN, HIGH);
  } else if (strcmp(type, "off") == 0) {
    ledState = false;
    digitalWrite(LED_PIN, LOW);
  } else if (strcmp(type, "value") == 0) {
    int v = doc["value"] | 0;       // slider 0-255; LED on when > 0
    ledState = v > 0;
    digitalWrite(LED_PIN, ledState ? HIGH : LOW);
  }

  Serial.print("[CMD] ");
  Serial.println(type);

  // Acknowledge so the dashboard marks the command confirmed.
  if (strlen(cmdId) > 0) {
    StaticJsonDocument<96> ack;
    ack["command_id"] = cmdId;
    ack["status"] = "executed";
    char ackBuf[96];
    serializeJson(ack, ackBuf);
    mqtt.publish(topicAck.c_str(), ackBuf);
  }

  publishTelemetry();
}

void connectMQTT() {
  while (!mqtt.connected()) {
    Serial.println("[MQTT] Connecting...");
    // Token is used as client id, username AND password. LWT marks the
    // device offline if the connection drops.
    if (mqtt.connect(DEVICE_TOKEN, DEVICE_TOKEN, DEVICE_TOKEN,
                     topicStatus.c_str(), 1, true, R"({"status":"offline"})")) {
      Serial.println("[MQTT] Connected.");
      mqtt.subscribe(topicCommand.c_str());
      mqtt.publish(topicStatus.c_str(), R"({"status":"online"})", true);
    } else {
      Serial.print("[MQTT] Failed, rc=");
      Serial.println(mqtt.state());
      delay(3000);
    }
  }
}

void setup() {
  Serial.begin(115200);
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);

  topicTelemetry = String("iotaps/") + DEVICE_TOKEN + "/telemetry";
  topicCommand   = String("iotaps/") + DEVICE_TOKEN + "/command";
  topicStatus    = String("iotaps/") + DEVICE_TOKEN + "/status";
  topicAck       = String("iotaps/") + DEVICE_TOKEN + "/ack";

  connectWiFi();
  mqtt.setServer(IOTAPS_SERVER, IOTAPS_PORT);
  mqtt.setCallback(onCommand);
  mqtt.setBufferSize(512);
  connectMQTT();
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) connectWiFi();
  if (!mqtt.connected()) connectMQTT();
  mqtt.loop();

  if (millis() - lastTelemetry >= TELEMETRY_INTERVAL) {
    lastTelemetry = millis();
    publishTelemetry();
  }
}
`;
}

export default buildBlinkSketch;
